# Generated by Django 4.1.1 on 2022-10-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', through='articles.ArticleScope', to='articles.tag', verbose_name='Тематики статьи'),
        ),
    ]
